- color: 198be8
  description: oncall for jit
  name: 'oncall: jit'
- color: daf222
  description: default
  name: ciflow/default
- color: daf222
  description: topic1
  name: ciflow/extra
- color: daf222
  description:
  name: ciflow/cuda
