- color: 198be8
  description: oncall for jit
  name: 'oncall: jit'
- color: 198be8
  description: ok-to-test
  name: 'ok-to-test'
- color: daf222
  description: topic1
  name: ci/topic1
- color: daf222
  description:
  name: ci/topic2
- color: daf222
  description:
  name: ci/topic3
- color: daf222
  description:
  name: ci/topic4
