version: 2.1

jobs:
  update_ubuntu_mirror:
    machine:
      image: "ubuntu-2004:202104-01"
    steps:
      - checkout
      - run: cat /etc/apt/sources.list
      - run: sudo sed -i -e 's/http:\/\/.*archive/mirror:\/\/mirrors/' -e 's/\/ubuntu\//\/mirrors.txt/' /etc/apt/sources.list
      - run: sudo time apt-get update -qq
      - run: sudo apt-get -y install moreutils expect-dev

workflows:
  build:
    jobs:
      - update_ubuntu_mirror
