# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  pull_request:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-18.04
    container:
      image: zhouzhuojie/cilint-clang-tidy

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # to allow tools/clang_tidy.py to do its thing

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: |
          cd "${GITHUB_WORKSPACE}"
          set -eux
          git remote add upstream https://github.com/pytorch/pytorch
