name: comments_bot

on:
  issue_comment:
    types: [edited]
  pull_request:

jobs:
  dispatch_labels:
    if: github.event.issue.pull_request
    runs-on: ubuntu-latest
    steps:
      - uses: hmarr/debug-action@v2
      - name: ciflow
        uses: zhouzhuojie/ciflow@dd1a0a8c85618585b76a611ae848a8527eb18b5e
        with:
          role: dispatcher
          comment-head-fixture: '# 📚 CIFlow Test Plan'
          comment-body-fixture: |
            - [x] ci/default
              - ciflow_lint.yml
              - ciflow_linux.yml
              - ciflow_windows.yml
              - ciflow_mac.yml
            - [ ] ci/extra
              - ciflow_linux_extra.yml
              - ciflow_windows_extra.yml
              - ciflow_mac_extra.yml
            - [ ] ci/cuda
              - ciflow_windows_cuda.yml