name: comments_bot

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

on:
  issue_comment:
  pull_request:

jobs:
  dispatch_labels:
    if: github.event.issue.pull_request
    runs-on: ubuntu-latest
    steps:
      - name: ciflow
        uses: zhouzhuojie/ciflow@b59f44dcc2fe590a79f51c206c36c16199f7f647
        with:
          comment-body: |
            - [x] ci/default
              - ciflow_lint.yml
              - ciflow_linux.yml
              - ciflow_windows.yml
              - ciflow_mac.yml
            - [ ] ci/extra
              - ciflow_linux_extra.yml
              - ciflow_windows_extra.yml
              - ciflow_mac_extra.yml
            - [ ] ci/cuda
              - ciflow_windows_cuda.yml