name: ci/topic4

on:
  pull_request:
  push:
    branches:
      - master
      - main

jobs:
  label_guard:
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request' || contains(github.event.pull_request.labels.*.name, 'ci/topic4')
    steps:
      - run: echo "noop"
  topic4_gha_job1:
    needs: [label_guard]
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "topic4_gha_job1"