name: ci/topic2

on:
  pull_request:
    types: [opened, labeled, unlabeled, synchronize]
  push:
    branches:
      - master
      - main

jobs:
  label_guard:
    runs-on: ubuntu-latest
    if: ${{ !(github.event_name == "pull_request") || contains(github.event.pull_request.labels.*.name, github.workflow)}}
    steps:
      - run: echo "noop"
  topic2_gha_job1:
    needs: [label_guard]
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "topic2_gha_job1"