name: ciflow_mac_extra

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

on:
  pull_request:
  push:
    branches:
      - master
      - main

jobs:
  label_guard:
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request' || contains(github.event.pull_request.labels.*.name, 'ci/extra')
    steps:
      - run: echo "noop"
  mac_extra_1:
    needs: [label_guard]
    runs-on: ubuntu-latest
    steps:
      - run: sleep 30s
  mac_extra_2:
    needs: [label_guard]
    runs-on: ubuntu-latest
    steps:
      - run: sleep 30s
