name: comments_bot

on: issue_comment

jobs:
  rerun_workflow:
    name: Rerun PR comment
    if: github.event.issue.pull_request
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v2
        with:
          script: |
            // search pull requests' branch
            const pr = await github.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.issue.number,
            });
          
            const ref = pr.data.head.ref; 
          
            const runs = await github.actions.listWorkflowRuns({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: "dispatch.yml",
              branch: ref,
            });
            
            const lastDispatchRun = runs.data.workflow_runs[0];
            core.debug(lastDispatchRun);
            
            const body = context.payload.comment.body;
            if (body.includes("please_rerun")) {
              github.actions.reRunWorkflow({
                owner: context.repo.owner,
                repo: context.repo.repo,
                run_id: lastDispatchRun.id,
              });
            }
            
            
            
