name: comments_bot

on: issue_comment

jobs:
  rerun_workflow:
    name: Rerun PR comment
    if: github.event.issue.pull_request
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v2
        with:
          script: |
            core.debug(JSON.stringify(github.event));
            core.debug(JSON.stringify(context));
            core.debug(Object.getOwnPropertyNames(github.actions));
