name: label dispatch

on:
  pull_request:
    types: [opened, labeled, unlabeled, synchronize]

jobs:
  dispatch:
    runs-on: ubuntu-latest
    outputs:
      plan: ${{steps.main.outputs.plan}}
    if: ${{github.event.pull_request.labels.*.name[0]}}
    env:
      PR: ${{toJSON(github.event.pull_request)}}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
          architecture: x64
      - id: main
        run: .github/dispatch/main.py
  topic1:
    needs: [dispatch]
    if: contains(fromJSON(needs.dispatch.outputs.plan).topics, 'topic1')
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo plan: "${{needs.dispatch.outputs.plan}}"
  topic2:
    needs: [dispatch]
    if: contains(fromJSON(needs.dispatch.outputs.plan).topics, 'topic2')
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo plan: "${{needs.dispatch.outputs.plan}}"
  topic3:
    needs: [dispatch]
    if: contains(fromJSON(needs.dispatch.outputs.plan).topics, 'topic3')
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo plan: "${{needs.dispatch.outputs.plan}}"
  topic4:
    needs: [dispatch]
    if: contains(fromJSON(needs.dispatch.outputs.plan).topics, 'topic4')
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo plan: "${{needs.dispatch.outputs.plan}}"
  topic1_gha_job1:
    needs: [topic1]
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "topic1_gha_job1"
  topic1_gha_job2:
    needs: [topic1]
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "topic1_gha_job2"
  topic1_circleci:
    needs: [topic1]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        topics: ${{fromJSON(needs.dispatch.outputs.plan).topics}}
    steps:
      - run: |
          echo "curl https://api.circleci.com"
  topic2_gha_job1:
    needs: [topic2]
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "topic2_gha_job1"