name: label dispatch

on:
  pull_request:
    types: [opened, labeled, unlabeled, synchronize]

jobs:
  dispatch:
    runs-on: ubuntu-latest
    if: ${{github.event.pull_request.labels.*.name[0]}}
    env:
      PR: ${{toJSON(github.event.pull_request)}}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
          architecture: x64
      - run: python .github/dispatch/main.py
  topic1:
    needs: [dispatch]
    if: contains(fromJSON(needs.dispatch.outputs.topics), 'topic1')
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo ctx: "${{needs.dispatch.outputs.ctx}}"
          echo topics: "${{needs.dispatch.outputs.topics}}"
  topic2:
    needs: [dispatch]
    if: contains(fromJSON(needs.dispatch.outputs.topics), 'topic2')
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo ctx: "${{needs.dispatch.outputs.ctx}}"
          echo topics: "${{needs.dispatch.outputs.topics}}"
  topic3:
    needs: [dispatch]
    if: contains(fromJSON(needs.dispatch.outputs.topics), 'topic3')
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo ctx: "${{needs.dispatch.outputs.ctx}}"
          echo topics: "${{needs.dispatch.outputs.topics}}"
  topic4:
    needs: [dispatch]
    if: contains(fromJSON(needs.dispatch.outputs.topics), 'topic4')
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo ctx: "${{needs.dispatch.outputs.ctx}}"
          echo topics: "${{needs.dispatch.outputs.topics}}"
