name: label dispatch

on:
  pull_request:
    types: [opened, labeled, unlabeled, synchronize]

jobs:
  dispatch_labels:
    runs-on: ubuntu-latest
    if: ${{github.event.pull_request.labels.*.name[0]}}
    steps:
      - run: echo "Check labels is not empty"
      - run: echo "Some heristics to triage which jobs to run"
      - run: echo "::set-output name=labels::${{github.event.pull_request.labels.*.name}}"
  build:
    needs: [dispatch_labels]
    strategy:
      matrix:
        label: ${{needs.dispatch_labels.outputs.labels.*.name}}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run a one-line script
        run: echo Hello, world from "${{matrix.label}}"!
